-- =============================================
-- SECTION: GET ALL DETAILS FROM TABLES
-- =============================================
SELECT * FROM PASSPORTRENEWALS;
SELECT * FROM TAXFILINGS;
SELECT * FROM LEGALINQUIRIES;
SELECT * FROM USERREQUESTS;
SELECT * FROM USERPROFILES;
SELECT * FROM ADMINPROFILES;

-- =============================================
-- SECTION: TRIGGERS
-- =============================================

-- TRIGGER: INSERT INTO USERREQUESTS AFTER INSERT ON PASSPORTRENEWALS
CREATE TRIGGER TRG_USERREQUEST_PASSPORTRENEWALS
ON PASSPORTRENEWALS
AFTER INSERT
AS
BEGIN
    INSERT INTO USERREQUESTS (USERID, REQUESTTYPE, RELATEDRECORDID, STATUS, CREATEDAT, CREATEDBY)
    SELECT 
        I.USERID,                       
        'PASSPORTRENEWAL',              
        1,                
        'PENDING',
        GETUTCDATE(),
        I.CREATEDBY
    FROM INSERTED I;
END;

-- TRIGGER: INSERT INTO USERREQUESTS AFTER INSERT ON TAXFILINGS
CREATE TRIGGER TRG_USERREQUEST_TAXFILING
ON TAXFILINGS
AFTER INSERT
AS
BEGIN
    INSERT INTO USERREQUESTS (USERID, REQUESTTYPE, RELATEDRECORDID, STATUS, CREATEDAT, CREATEDBY)
    SELECT 
        I.USERID,                       
        'TAXFILING',              
        1,                
        'PENDING',
        GETUTCDATE(),
        I.CREATEDBY
    FROM INSERTED I;
END;

-- TRIGGER: INSERT INTO USERREQUESTS AFTER INSERT ON LEGALINQUIRIES
CREATE TRIGGER TRG_USERREQUEST_LEGALINQUIRIES
ON LEGALINQUIRIES
AFTER INSERT
AS
BEGIN
    INSERT INTO USERREQUESTS (USERID, REQUESTTYPE, RELATEDRECORDID, STATUS, CREATEDAT, CREATEDBY)
    SELECT 
        I.USERID,                       
        'LEGALINQUIRIES',              
        1,                
        'PENDING',
        GETUTCDATE(),
        I.CREATEDBY
    FROM INSERTED I;
END;

-- =============================================
-- SECTION: STORED PROCEDURES
-- =============================================

-- STORED PROCEDURE: GET ALL USER PROFILE DETAILS
CREATE PROC GETALLDETAILSUSERS  
AS  
BEGIN
    SELECT * FROM USERPROFILES;
END;

SELECT U.FULLNAME, R.STATUS FROM UserProfiles U JOIN UserRequests R
ON U.UserId=R.UserId
WHERE R.STATUS='PENDING'
