export interface Taxfilling {
  taxFilingId?: number; // optional if generated by backend
  userId: number;
  firstName: string;
  lastName: string;
  ssn?: number;
  filingStatus: string;
  w2Income: number;
  freelance1099Income: number;
  standardDeduction: string;
  charitableDonations: number;
  mortgageInterestPaid: number;
  estimatedTaxRefund: number;
  createdAt?: string; // optional, backend generates
  createdBy: number;
}
